version: '3'
services:
    app:
        image: "lgm:${LGM_TAG}"
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/lgm?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
 #       ports:
 #           - 8088:8080
        networks:
            - web
            - default
        labels:
            - "traefik.enable=true"
            - "traefik.frontend.rule=Host:lgm.pentland.ml"
#            - "traefik.frontend.rule=PathPrefix:/jenkins"
            - "traefik.frontend.priority=2"
            - "traefik.basic.port=8080"
            - "traefik.basic.protocol=http"
            - "traefik.docker.network=web"
    db:
        image: mysql:5.7.20
        # volumes:
        #     - ~/volumes/jhipster/Lgm/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=lgm
        command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
        networks:
          - default

networks:
  web:
    external: true
